---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otbr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: otbr
  values:
    controllers:
      slzb-mr4:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"iot",
                "namespace": "kube-system",
                "ips": ["10.5.0.30/24", "fd22:ae86:237c:1::30/64"],
                "mac": "4a:e3:b1:72:c5:9d"
              }]
        containers:
          otbr: &container
            image:
              repository: ghcr.io/wittdennis/homeassistant-otbr
              tag: 4.2.2@sha256:80f35717025aa5a15ce593232c2531e67e123e3e439545d5320e35a7c60da017
            env: &env
              BACKBONE_IF: net1
              BAUDRATE: "460800"
              FIREWALL: "1"
              NAT64: "1"
              NETWORK_DEVICE: "10.5.0.61:6638"
              S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: 1
              S6_READ_ONLY_ROOT: 1
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add:
                  - NET_ADMIN
                  - NET_RAW
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 512Mi
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /node/state
                    port: &port 8081
              readiness: *probe
      slzb-m5u:
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [
                {
                  "name":"iot",
                  "namespace": "kube-system",
                  "interface": "net1",
                  "ips": ["10.5.0.29/24", "fd22:ae86:237c:1::29/64"],
                  "mac": "64:16:7F:61:46:5C"
                }
              ]
        containers:
          otbr:
            <<: *container
            env:
              <<: *env
              NETWORK_DEVICE: "10.5.0.196:6638"
    defaultPodOptions:
      securityContext:
        sysctls:
          - name: net.ipv6.conf.all.forwarding
            value: "1"
          - name: net.ipv6.conf.net1.accept_ra
            value: "2"
          - name: net.ipv6.conf.net1.accept_ra_rt_info_max_plen
            value: "64"
    service:
      slzb-mr4:
        controller: slzb-mr4
        ports:
          http:
            port: *port
      slzb-m5u:
        controller: slzb-m5u
        ports:
          http:
            port: *port

    persistence:
      data:
        existingClaim: otbr
        advancedMounts:
          slzb-mr4:
            otbr:
              - path: /data
                subPath: slzb-mr4
          slzb-m5u:
            otbr:
              - path: /data
                subPath: slzb-m5u
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /run
            subPath: run
      tun:
        type: hostPath
        hostPath: /dev/net/tun
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/net/tun
