---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: staub-scraper
spec:
  chartRef:
    kind: OCIRepository
    name: staub-scraper
  interval: 1h
  values:
    controllers:
      staub-scraper:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/jimmy-ungerman/staubscraper
              tag: 2.0.0@sha256:62c03914a4f94ea56c7b90b3525c52f6adf80cea95591ccbb36aecec4a99b8f0
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            resources:
              requests:
                cpu: "10m"
                memory: "50Mi"
              limits:
                cpu: "200m"
                memory: "512Mi"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 5123
                  initialDelaySeconds: 25
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 3
              readiness: *probes
    service:
      app:
        ports:
          http:
            port: 5123
    persistence:
      tmp:
        type: emptyDir