---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: staub-scraper
spec:
  chartRef:
    kind: OCIRepository
    name: staub-scraper
  interval: 1h
  values:
    controllers:
      staub-scraper:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/jimmy-ungerman/staubscraper
              tag: main@sha256:6a208f74e9b7fd47da3ac1dc4163853d85f2825d7f28e96610fcfc96be7f22a4 
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            resources:
              requests:
                cpu: "500m"
                memory: "1024Mi"
              limits:
                cpu: "1000m"
                memory: "2048Mi"
    service:
      app:
        ports:
          http:
            port: 5123
    persistence:
      tmp:
        type: emptyDir