---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: psu-parlay
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: psu-parlay
  values:
    app:
      storage: "2Gi"
      image:
        repository: ghcr.io/jimmy-ungerman/psu-parlay
        tag: 1.0.12@sha256:189c77e8e7616891d965d27618115d0ed44dcb555fbcfb06e544b5dab84c29d2
    httproute:
      enabled: true
      parentRefs:
        - name: envoy-external
          namespace: network
      hostnames:
        - psuparlay.porkboi.io