---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: psu-parlay
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: psu-parlay
  values:
    app:
      storage: "2Gi"
      image:
        repository: ghcr.io/jimmy-ungerman/psu-parlay
        tag: 1.0.10@sha256:ce74ed63830d90d9b2bb2543a711a5cfd783499c0e788c5a7f73ea70d2d8c93d
    httproute:
      enabled: true
      parentRefs:
        - name: envoy-external
          namespace: network
      hostnames:
        - psuparlay.porkboi.io