---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: psu-parlay
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: psu-parlay
  values:
    app:
      storage: "2Gi"
      image:
        repository: ghcr.io/jimmy-ungerman/psu-parlay
        tag: 1.0.4@sha256:fdaee4b538e17f03b24718c1c474d74626d44fde522c533a63e031cf195cbcfc
    httproute:
      enabled: true
      parentRefs:
        - name: envoy-external
          namespace: network
      hostnames:
        - psuparlay.porkboi.io