---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/notification.toolkit.fluxcd.io/provider_v1beta3.json
kind: Provider
metadata:
  name: github-status
spec:
  type: github
  address: https://github.com/jimmy-ungerman/pork3s
  secretRef:
    name: github-status-token-secret