---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/alerts
  - ../../components/kopiur/secret

resources:
  - ./namespace.yaml
  - ./bazarr/ks.yaml
  - ./chaski/ks.yaml
  - ./deduparr/ks.yaml
  - ./home-assistant/ks.yaml
  - ./karakeep/ks.yaml
  - ./mosquitto/ks.yaml
  - ./plex/ks.yaml
  - ./profilarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./psu-parlay/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./seerr/ks.yaml
  - ./sonarr/ks.yaml
  - ./staubscraper/ks.yaml
  - ./zigbee/ks.yaml
