---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: big10survivor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: big10survivor-secret
    template:
      data:
        JWT_SECRET: "{{ .JWT_SECRET }}"
  dataFrom:
    - extract:
        key: big10survivor
