---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app profilarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: profilarr
  values:
    controllers:
      profilarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/dictionarry-hub/profilarr
              tag: v2.2.0@sha256:ddcdd0f340043c2ec0a85ca74b9a6be9be42b1c0288c75fc36a26a43f695860b
            env:
              TZ: America/Boise
              PUID: 1000
              GUID: 1000
              ORIGIN: https://profilarr.porkboi.io
              AUTH: off
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 6868
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
            resources:
              requests:
                cpu: 25m
              limits:
                memory: 1Gi
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.porkboi.io"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
