---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: psu-parlay-pr-19
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: psu-parlay-staging
  values:
    app:
      storage: "2Gi"
      image:
        repository: ghcr.io/jimmy-ungerman/psu-parlay
        tag: pr-19@sha256:ce70f44bfcf9823f516e09d66d37b145c36861eb910acc6e1f4301e95c69a81f # updated automatically by deploy-staging workflow
    httproute:
      enabled: true
      parentRefs:
        - name: envoy-internal
          namespace: network
      hostnames:
        - psuparlay-staging.porkboi.io
