---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: psu-parlay-pr-8
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: psu-parlay-staging
  values:
    app:
      storage: "2Gi"
      image:
        repository: ghcr.io/jimmy-ungerman/psu-parlay
        tag: pr-8@sha256:b390819d8835e5699acf5dce5a545e8686c1f80f608c6d0367525963daa14d98 # updated automatically by deploy-staging workflow
    httproute:
      enabled: true
      parentRefs:
        - name: envoy-internal
          namespace: network
      hostnames:
        - psuparlay-staging.porkboi.io
