---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: psu-parlay-pr-10
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: psu-parlay-staging
  values:
    app:
      storage: "2Gi"
      image:
        repository: ghcr.io/jimmy-ungerman/psu-parlay
        tag: pr-10@sha256:b48f95187358a4dcfd31cdaf9e8cab3f224e82ac7ccb6359e864a72da9ec3346 # updated automatically by deploy-staging workflow
    httproute:
      enabled: true
      parentRefs:
        - name: envoy-internal
          namespace: network
      hostnames:
        - psuparlay-staging.porkboi.io
