apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:HnzysK6UMzJaTMm+goSdESvC0TKjkQpm6Iym2u+MxkrxewFhqqbsi5DZAiJwadSRNy3CvH+eBGTpBa45xxprdCybWtq8DrnnpHY=,iv:aQsGKAL+zrtZMKtk8kVYTm6iORgUllW5olSzSw5uNa8=,tag:r0g2LDe89dAme52SyRS+xg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age160xmmjztxl2n8pqfexusejr3xf9wz3f8ma2jpxjqde34n2jp795qw86wv9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTXBHOW9aZUk1VWRDckpT
        aXkvOWtTdVE5eGd6TUtwZ2dONWV4NGp5M25ZCnBDaDl4NDAzWTJidVJubkFNYmky
        UHJJaUJHeWpBSVQ4TXVHWk5YcWtwNDQKLS0tIG9icFJpRDd6SUx0NXlQODkrdUth
        S1RvNjVtWEUxOHdROCtrd0JDU0FUTVUKGVeS2oX+7SVgu3YvNiKP8LGsBpCfPCWu
        uvYM5PfJ77GVSPgYTFkoZP5e2xvyFoI7rEMbvsnqIoCiknHtOdEaAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-28T23:35:35Z"
  mac: ENC[AES256_GCM,data:WUBfX568s8vIVALClnNrU869uoAvOrltetdHEt2Z5E5G3khssgzdEQqQSSoXuygL/o9apx6nem1OYLqgL8UioNZZOfID+c2TMyeHb/X5MNqDUovT6amY4avJ+l5+UdqU0GXpjDLo2fYhXy+LsKCnrwi7wJpdmNQ4lrcoiSjg14s=,iv:WJnIWBIlj/8F1xdluBI5stcuBXIM6OCBVdsJ9hJF3SA=,tag:aUaVorEOB1vI+xeq8KFQaA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.2
